// Shared visual tokens for the four primary research workspace pages.
// Keep colors as hex values: charts and badges append alpha values to them.
export const M = {
  canvas: '#E2E5E8',
  canvas2: '#DCE0E4',
  sidebar: '#151D23',
  card: '#ECEFF1',
  cardElev: '#F0F2F4',
  well: '#E7EAED',
  line: '#D5DAE0',
  line2: '#C4CBD3',
  ink: '#101720',
  inkDim: '#394553',
  inkFaint: '#5F6B7A',
  accent: '#365D82',
  accentSoft: '#E0E7EE',
  accentBright: '#345D83',
  pos: '#396C59',
  neg: '#A34B51',
  warn: '#896D37',
  canvasInk: '#101720',
  canvasInkDim: '#394553',
  canvasInkFaint: '#5F6B7A',
  dangerWell: '#F3E3E6',
  shadow: 'none',
  radius: 5,
  controlRadius: 3,
  panelPadding: 14,
  sectionGap: 12,
  serif: "'Newsreader', Georgia, 'Times New Roman', serif",
  sans: "Inter, ui-sans-serif, system-ui, sans-serif",
  mono: "'IBM Plex Mono', ui-monospace, monospace",
} as const;
