"""
Thematic agent — translates a ResearchPriority into a structured
ThematicMap of candidates with consensus/variant analysis.

See agents/thematic_agent_contract.md for the behavioral contract (rules
TA-1 through TA-20) that this agent must enforce via prompt design and
validation.

Implementation arrives in Phase 2.2.4. This module currently contains only
the function signature and exception types so downstream modules (test
harness, eval scoring) can import against a stable API.
"""
from __future__ import annotations

from typing import Literal, Optional, Union

from pydantic import Field, field_validator

from src.agent_system.schemas.common import BaseSchema, Catalyst, UnitInterval
from src.agent_system.schemas.regime import (
    ClarificationRequest,
    RegimeState,
    ResearchPriority,
)
from src.agent_system.schemas.thematic import (
    Candidate,
    ConsensusType,
    ExclusionRecord,
    FitStrengthComponents,
    InstrumentType,
    ResearchDepth,
    RejectedQuickItem,
    ThematicMap,
    VariantStrength,
    compute_fit_strength_from_components,
)


class ThematicAgentValidationError(Exception):
    """
    Raised when the thematic agent fails to produce valid structured
    output after one retry. The caller should surface this to the user
    as a system error rather than substituting a stub ThematicMap.
    Silently producing invalid data is explicitly forbidden by contract
    rule TA-10.
    """


class _ThematicDerivedEvidence(BaseSchema):
    """OpenAI-compatible thematic evidence subset for agent output."""

    source_type: Literal["derived", "verification_required"] = "derived"
    claim: str = Field(min_length=1, max_length=2000)
    supports: bool
    computation: str = Field(min_length=1, max_length=500)
    upstream_claims: list[str] = Field(min_length=1, max_length=20)
    notes: str = Field(default="", max_length=2000)


class _ThematicCandidate(BaseSchema):
    """
    OpenAI-compatible candidate output restricted to DerivedEvidence.

    The public Candidate accepts the full Evidence union. The thematic agent
    only has regime and priority context available, so DerivedEvidence is both
    the appropriate output type and compatible with structured output.
    """

    ticker: str = Field(min_length=1, max_length=20)
    instrument_type: InstrumentType
    name: str = Field(default="", max_length=200)

    @field_validator("ticker", mode="before")
    @classmethod
    def _validate_ticker_format(cls, v: str) -> str:
        if isinstance(v, str) and ("/" in v or any(ch.isspace() for ch in v)):
            raise ValueError(
                "ticker must be a single symbol (no '/' or whitespace). "
                "For pair trades, use one leg's ticker (the long leg, "
                "conventionally) and describe the pair in thematic_fit; "
                "set instrument_type=PAIR. Got: " + repr(v)
            )
        return v

    thematic_fit: str = Field(min_length=1, max_length=1000)
    fit_strength: UnitInterval = 0.0
    fit_strength_components: FitStrengthComponents
    fit_evidence: list[_ThematicDerivedEvidence] = Field(
        default_factory=list,
        max_length=15,
    )
    consensus_view: str = Field(min_length=1, max_length=2000)
    consensus_type: ConsensusType = ConsensusType.NARRATIVE
    potential_variant_view: str = Field(default="", max_length=2000)
    variant_strength: VariantStrength
    variant_evidence: list[_ThematicDerivedEvidence] = Field(
        default_factory=list,
        max_length=15,
    )
    catalysts: list[Catalyst] = Field(default_factory=list, max_length=10)
    priority_rank: int = Field(ge=1, le=15)
    recommended_research_depth: ResearchDepth
    theme_tags: list[str] = Field(default_factory=list, max_length=10)

    def to_candidate(self) -> Candidate:
        """Convert structured-output shape to the public Candidate schema."""
        data = self.model_dump()
        data["fit_strength"] = compute_fit_strength_from_components(
            self.fit_strength_components
        )
        return Candidate.model_validate(data)


class _ThematicMapOutput(BaseSchema):
    """
    OpenAI-compatible thematic-map shape.

    The source priority is input lineage rather than generated analysis. It is
    attached from the caller's validated ResearchPriority at the public-schema
    boundary instead of being regenerated by the model.
    """

    candidates: list[_ThematicCandidate] = Field(default_factory=list, max_length=30)
    excluded: list[ExclusionRecord] = Field(default_factory=list, max_length=50)
    rejected_quick: list[RejectedQuickItem] = Field(default_factory=list, max_length=30)
    mapping_logic: str = Field(min_length=20, max_length=3000)
    universe_considered: int = Field(default=0, ge=0)

    def to_thematic_map(self, source_priority: ResearchPriority) -> ThematicMap:
        """Attach upstream lineage and convert to the public ThematicMap schema."""
        return ThematicMap(
            source_priority=source_priority,
            candidates=[candidate.to_candidate() for candidate in self.candidates],
            excluded=self.excluded,
            rejected_quick=self.rejected_quick,
            mapping_logic=self.mapping_logic,
            universe_considered=self.universe_considered,
        )


class _ThematicAgentResponse(BaseSchema):
    """
    Internal wrapper for OpenAI structured output. The agent returns
    exactly one of thematic_map/clarification populated; the function
    unpacks and returns the populated one.
    """

    response_kind: Literal["thematic_map", "clarification"]
    thematic_map: Optional[_ThematicMapOutput] = None
    clarification: Optional[ClarificationRequest] = None


async def translate_priority_to_candidates(
    priority: ResearchPriority,
    regime_state: RegimeState,
    *,
    candidate_universe: Optional[list[str]] = None,
    enable_clarification: bool = True,
) -> Union[ThematicMap, ClarificationRequest]:
    """
    Translate a ResearchPriority into a structured ThematicMap of candidates.

    See agents/thematic_agent_contract.md for the full behavioral contract
    (rules TA-1 through TA-20) that this function enforces via prompt
    design and validation.

    Args:
        priority: The ResearchPriority produced by the macro agent. The
            agent reads theme, rationale, edge_hypothesis, sub_questions,
            and supporting_evidence to identify candidates that fit the
            priority's specific thesis. This priority is embedded as-is
            in the returned ThematicMap's source_priority field; the
            agent does not modify or reframe it.
        regime_state: Current regime context. The agent uses this for its
            own grounding when assessing consensus and variant views for
            each candidate.
        candidate_universe: Optional explicit constraint on which tickers
            the agent may choose from. None (default) means the agent
            generates its own candidate set from its priors plus the
            priority's thesis. This parameter exists for future use; in
            v1 implementation it will typically be None until empirical
            evidence shows we need a constrained universe.
        enable_clarification: If False, the agent must produce a
            ThematicMap regardless of priority quality (used by the test
            harness for output comparability). If True (default), abstract
            or thesis-insufficient priorities may return a
            ClarificationRequest instead.

    Returns:
        ThematicMap if the priority is researchable as candidates.
        ClarificationRequest if the priority's thesis is genuinely too
            abstract for the agent to identify a concrete candidate set,
            and enable_clarification is True.

    Raises:
        ThematicAgentValidationError: If the agent fails to produce valid
            structured output after one retry.
        ValueError: If priority is None or has obviously malformed fields
            (the caller should validate before invoking).
    """
    # Input validation
    if priority is None:
        raise ValueError("priority cannot be None")
    if regime_state is None:
        raise ValueError("regime_state cannot be None")

    # Build the prompt
    from src.agent_system.agents.thematic_agent_prompts import (
        SYSTEM_PROMPT_TEMPLATE,
        render_priority_context,
    )
    from src.agent_system.agents.macro_agent_prompts import render_regime_context
    from src.agent_system.llm.client import StructuredOutputError, parse_structured
    from src.agent_system.llm.config import THEMATIC_AGENT_MODEL

    priority_context = render_priority_context(priority)
    regime_context = render_regime_context(regime_state)
    system_prompt = SYSTEM_PROMPT_TEMPLATE.format(
        priority_context=priority_context,
        regime_context=regime_context,
    )
    # The original priority is attached programmatically after structured
    # generation, so the model cannot modify upstream lineage.
    user_message = (
        f"Produce a candidate map for the following priority. Do not emit "
        f"source_priority; the system attaches the original priority after "
        f"validating your output.\n\n"
        f"Priority theme: {priority.theme}\n"
        f"Priority rank: {priority.priority_rank}\n"
        f"Expected edge decay: {priority.expected_edge_decay.value}\n"
    )

    # Use OpenAI-compatible schemas that expose DerivedEvidence only; the
    # public ThematicMap contains Evidence unions unsupported by response_format.
    response_schema = (
        _ThematicMapOutput if not enable_clarification else _ThematicAgentResponse
    )

    try:
        result = parse_structured(
            system=system_prompt,
            user=user_message,
            model=THEMATIC_AGENT_MODEL,
            response_schema=response_schema,
            purpose=f"thematic agent translate_priority_to_candidates: {priority.theme[:60]}",
            temperature=0.3,
            timeout_seconds=300,
        )
    except StructuredOutputError as e:
        raise ThematicAgentValidationError(str(e)) from e

    if not enable_clarification:
        return result.to_thematic_map(priority)

    # Unpack the union wrapper
    if result.thematic_map is not None and result.clarification is not None:
        raise ThematicAgentValidationError(
            "Agent returned both thematic_map and clarification — invalid output"
        )
    if result.thematic_map is not None:
        return result.thematic_map.to_thematic_map(priority)
    if result.clarification is not None:
        return result.clarification
    raise ThematicAgentValidationError(
        "Agent returned neither thematic_map nor clarification — invalid output"
    )
